### PR TITLE
Adapt environment to allow changes to timescale and framerates for more control

### PR DESCRIPTION
**Pull request by kozzy97**
It was identified that some objects evolve in the environment sensitive to time, and large timescales (such as the default of 300) limited their behaviour. The AnimalAIEnvironment class has been changed to allow the user to change timescale, targetFrameRate and captureFrameRate. An example script for playing with the environment has also been provided.

### CODE REVIEW

**Review by wschella — APPROVED** [review]
Added some comments, and removed the inference flag, as it didn't do anything anymore except set window size, which isn't relevant for the agent.

**Comment by alhasacademy96** [comment]
Hi peeps, I will review the code tonight but since Wout has already approved the pull, you can if you like merge as there are no conflicts with main :) 👍

**Comment by kozzy97** [comment]
Sure Ibrahim, take a look whenever you can, it would be good just to double check that it works for you before merging. No rush.

**Comment by alhasacademy96** [comment]
From what I understand, the primary changes made in the pull request are to allow dynamic setting of the timescale, target frame rate, and capture frame rate instead of using hard-coded class-level constants. This will provide more flexibility in configuring the AnimalAIEnvironment...(?).

If I missed something, let me know but the merge can be made as all my unit tests implemented on the pull are successful. Here are the unit tests I made (let me know if I missed something to test): 
```
import unittest
from unittest.mock import Mock, patch

# Mocking the UnityEnvironment to avoid actual Unity calls
class MockUnityEnvironment:
    def __init__(self, *args, **kwargs):
        pass

    def reset(self):
        pass

# Test suite for the AnimalAIEnvironment class
class TestAnimalAIEnvironment(unittest.TestCase):
    
    # Mocking UnityEnvironment to use MockUnityEnvironment
    @patch('mlagents_envs.environment.UnityEnvironment', new=MockUnityEnvironment)
    def test_initialization_default_parameters(self):
        env = AnimalAIEnvironment()
        self.assertIsNotNone(env)
        self.assertEqual(env.timescale, 1)
        self.assertEqual(env.targetFrameRate, 60)
        self.assertEqual(env.captureFrameRate, 0)
    
    @patch('mlagents_envs.environment.UnityEnvironment', new=MockUnityEnvironment)
    def test_initialization_custom_parameters(self):
        env = AnimalAIEnvironment(timescale=5, targetFrameRate=45, captureFrameRate=15)
        self.assertIsNotNone(env)
        self.assertEqual(env.timescale, 5)
        self.assertEqual(env.targetFrameRate, 45)
        self.assertEqual(env.captureFrameRate, 15)
    
    def test_get_obs_dict_with_camera_only(self):
        env = AnimalAIEnvironment(useCamera=True, useRayCasts=False)
        obs = [
            [[1, 2, 3]],
            [[0.5, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]]
        ]
        result = env.get_obs_dict(obs)
        self.assertEqual(result["camera"], [1, 2, 3])
        self.assertEqual(result["health"], 0.5)
    
    def test_get_obs_dict_with_raycast_only(self):
        env = AnimalAIEnvironment(useCamera=False, useRayCasts=True)
        obs = [
            [[1, 2, 3]],
            [[0.5, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]]
        ]
        result = env.get_obs_dict(obs)
        self.assertEqual(result["rays"], [1, 2, 3])
        self.assertEqual(result["health"], 0.5)
    
    def test_get_obs_dict_with_both_camera_and_raycast(self):
        env = AnimalAIEnvironment(useCamera=True, useRayCasts=True)
        obs = [
            [[1, 2, 3]],
            [[4, 5, 6]],
            [[0.5, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]]
        ]
        result = env.get_obs_dict(obs)
        self.assertEqual(result["camera"], [1, 2, 3])
        self.assertEqual(result["rays"], [4, 5, 6])
        self.assertEqual(result["health"], 0.5)
    
    @patch('mlagents_envs.environment.UnityEnvironment', new=MockUnityEnvironment)
    def test_create_engine_config_side_channel_play(self):
        env = AnimalAIEnvironment(play=True)
        engine_config_channel = env.create_engine_config_side_channel()
        self.assertIsNotNone(engine_config_channel)
    
    @patch('mlagents_envs.environment.UnityEnvironment', new=MockUnityEnvironment)
    def test_create_engine_config_side_channel_train(self):
        env = AnimalAIEnvironment(play=False)
        engine_config_channel = env.create_engine_config_side_channel()
        self.assertIsNotNone(engine_config_channel)

if __name__ == "__main__":
    unittest.main()
```

**Review by alhasacademy96 — APPROVED** [review]

**Comment by kozzy97** [comment]
Thanks all. Merging now.

**Comment by wschella** [comment]
Are these unit tests in the repo somewhere?

**Comment by wschella** [comment]
No no. Just curious, I've just never seen a nicely developed set op tests not incorporated in a permanent test suite. But it makes sense!

**Comment by alhasacademy96** [comment]
Much appreciated Wout ;)
Thank man :)))

**Pull request merged**
